version : '3'

services:
    frontend:
        depends_on:
          - backend
        image: topics-explorer-frontend
        ports:
          - "443:443"
    backend:
        depends_on:
          - appdatabase
        image: topics-explorer-backend
        ports:
          - "8080:8080"
          - "8443:8443"
        environment:
          - KEYSTOREPASSWD=$KEYSTOREPASSWD_HOST
          - DB_PASSWORD=$DB_PASSWORD
          - EMAIL_PASSWD=$EMAIL_PASSWD
    appdatabase:
        image: postgres
        environment:
          - POSTGRES_PASSWORD=$DB_PASSWORD
          - POSTGRES_DB=topicsexplorer
        volumes:
          - ../database/postgresql-data:/var/lib/postgresql/data
