version : '3'

services:
    frontend:
        depends_on:
          - backend
        image: topics-explorer-frontend
        ports:
          - "3000:80"
    backend:
        depends_on:
          - appdatabase
        image: topics-explorer-backend
        ports:
          - "8080:8080"
          - "443:443"
    appdatabase:
        image: postgres
        environment:
          - POSTGRES_PASSWORD=${DBPASSWORD}
          - POSTGRES_DB=topicsexplorer
        volumes:
          - ../database/postgresql-data:/var/lib/postgresql/data
