version : '3'

services:
    frontend:
        depends_on:
          - backend
        image: topics-explorer-frontend-dev
        ports:
          - "3000:3000"          
        volumes:
          - ../topics-explorer-frontend:/app        
    backend:
        depends_on:
          - appdatabase
        image: topics-explorer-backend-dev
        ports:
          - "8080:8080"
          - "8443:8443"
        volumes:
          - ../topics-explorer-backend:/backend          
        environment:
          - KEYSTOREPASSWD=$KEYSTOREPASSWD_HOST
          - DB_PASSWORD=$DB_PASSWORD
          - EMAIL_PASSWD=$EMAIL_PASSWD
    appdatabase:
        image: postgres
        environment:
          - POSTGRES_PASSWORD=$DB_PASSWORD
          - POSTGRES_DB=topicsexplorer
        volumes:
          - ../database/postgresql-data:/var/lib/postgresql/data
    mailserver:
      image: maildev/maildev
      ports:
        - "1080:1080"
        - "1025:1025"
